version: '3.8'

services:
  fby_example:
    image: postgres:16-alpine
    container_name: fby_example
    environment:
      POSTGRES_DB: fby_example
      POSTGRES_USER: fby_example
      POSTGRES_PASSWORD: fby_example
    ports:
      - "5433:5432"

  fby_test:
    image: postgres:16-alpine
    container_name: fby_test
    environment:
      POSTGRES_DB: fby_test
      POSTGRES_USER: fby_test
      POSTGRES_PASSWORD: fby_test
    ports:
      - "5432:5432"
