version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fby_example
    environment:
      POSTGRES_DB: fby_example
      POSTGRES_USER: fby_example
      POSTGRES_PASSWORD: fby_example
    ports:
      - "5432:5432"
